name: 'workflow_run status'
description: 'Associate workflow_run status with the base commit of workflow_run triggered event'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
